"""The C# emitter half of FFI binding generation: consumes the buckminster-ffi-dump JSON (whose raw_params are authored by the Rust macros, never re-derived here) and emits the raw [LibraryImport] layer, idiomatic wrappers, mirrored types, and per-struct layout tests. Output is a build artifact, never checked in: the Generated/ directories are owned outright -- files this module did not emit are deleted.

The type vocabulary is deliberately narrow; anything outside it is a loud GenError, never a new marshalling layer. Shapes that are in-vocabulary but have no converted consumer yet (slice-in, ref in-out) error with a pointer at their first consumer, so no emitter line ships unexercised."""

import json
import os
from dataclasses import dataclass


class GenError(Exception):
    """A loud codegen failure: vocabulary violation, dump/derivation mismatch, or schema drift."""


_HEADER = "// GENERATED by tools/lib/ffigen.py from the buckminster-ffi-dump metadata -- DO NOT EDIT; regenerate with ./tool.bat build.\n"

# Semantic scalars (wrapper layer); raw signatures never contain bool (the macro records u8).
_SCALAR_CS = {
    "i8": "sbyte",
    "u8": "byte",
    "i16": "short",
    "u16": "ushort",
    "i32": "int",
    "u32": "uint",
    "i64": "long",
    "u64": "ulong",
    "f32": "float",
    "f64": "double",
    "usize": "nuint",
    "bool": "bool",
}


def _expect_str(data: dict[str, object], key: str, where: str) -> str:
    value = data.get(key)
    if not isinstance(value, str):
        raise GenError(f"{where}: expected string '{key}', got {value!r}")
    return value


def _expect_bool(data: dict[str, object], key: str, where: str) -> bool:
    value = data.get(key)
    if not isinstance(value, bool):
        raise GenError(f"{where}: expected bool '{key}', got {value!r}")
    return value


def _expect_int(data: dict[str, object], key: str, where: str) -> int:
    value = data.get(key)
    if not isinstance(value, int) or isinstance(value, bool):
        raise GenError(f"{where}: expected int '{key}', got {value!r}")
    return value


def _expect_list(data: dict[str, object], key: str, where: str) -> list[dict[str, object]]:
    value = data.get(key)
    if not isinstance(value, list):
        raise GenError(f"{where}: expected list '{key}', got {value!r}")
    items: list[dict[str, object]] = []
    for entry in value:  # pyright: ignore[reportUnknownVariableType]
        if not isinstance(entry, dict):
            raise GenError(f"{where}: '{key}' entries must be objects, got {entry!r}")
        items.append({str(k): v for k, v in entry.items()})  # pyright: ignore[reportUnknownVariableType, reportUnknownArgumentType]
    return items


def _expect_str_list(data: dict[str, object], key: str, where: str) -> tuple[str, ...]:
    value = data.get(key)
    if not isinstance(value, list):
        raise GenError(f"{where}: expected string list '{key}', got {value!r}")
    result: list[str] = []
    for entry in value:  # pyright: ignore[reportUnknownVariableType]
        if not isinstance(entry, str):
            raise GenError(f"{where}: '{key}' entries must be strings, got {entry!r}")
        result.append(entry)
    return tuple(result)


def _expect_obj(data: dict[str, object], key: str, where: str) -> dict[str, object]:
    value = data.get(key)
    if not isinstance(value, dict):
        raise GenError(f"{where}: expected object '{key}', got {value!r}")
    return {str(k): v for k, v in value.items()}  # pyright: ignore[reportUnknownVariableType, reportUnknownArgumentType]


@dataclass(frozen=True)
class TypeRef:
    """A semantic (wrapper-layer) type from the dump."""

    kind: str
    scalar: str = ""
    mirror_name: str = ""
    elem: "TypeRef | None" = None


@dataclass(frozen=True)
class RawParam:
    """One raw extern parameter, verbatim from the macro-authored signature."""

    name: str
    kind: str
    scalar: str = ""
    mirror_name: str = ""


@dataclass(frozen=True)
class Param:
    name: str
    ty: TypeRef


@dataclass(frozen=True)
class Ret:
    name: str
    ty: TypeRef


@dataclass(frozen=True)
class Export:
    name: str
    symbol: str
    docs: tuple[str, ...]
    public: bool
    params: tuple[Param, ...]
    returns: tuple[Ret, ...]
    raw_params: tuple[RawParam, ...]


@dataclass(frozen=True)
class Field:
    name: str
    ty: TypeRef
    docs: tuple[str, ...]


@dataclass(frozen=True)
class Struct:
    name: str
    docs: tuple[str, ...]
    public: bool
    fields: tuple[Field, ...]


@dataclass(frozen=True)
class Method:
    name: str
    docs: tuple[str, ...]
    params: tuple[Param, ...]
    returns: tuple[Ret, ...]
    raw_params: tuple[RawParam, ...]


@dataclass(frozen=True)
class Trait:
    name: str
    docs: tuple[str, ...]
    vtable: str
    methods: tuple[Method, ...]


@dataclass(frozen=True)
class Variant:
    name: str
    value: int
    docs: tuple[str, ...]


@dataclass(frozen=True)
class Enum:
    name: str
    docs: tuple[str, ...]
    public: bool
    repr_scalar: str
    variants: tuple[Variant, ...]


def _parse_type(data: dict[str, object], where: str) -> TypeRef:
    kind = _expect_str(data, "kind", where)
    if kind == "scalar":
        return TypeRef(kind=kind, scalar=_expect_str(data, "scalar", where))
    if kind in ("str", "rid", "fn_ptr"):
        return TypeRef(kind=kind)
    if kind == "mirror":
        return TypeRef(kind=kind, mirror_name=_expect_str(data, "name", where))
    if kind in ("slice_in", "slice_out"):
        return TypeRef(kind=kind, elem=_parse_type(_expect_obj(data, "elem", where), where))
    if kind == "ref_in_out":
        # The inner type is not needed until this shape has a converted consumer; recording the kind is enough to reject it loudly today.
        return TypeRef(kind=kind)
    raise GenError(f"{where}: unknown semantic type kind '{kind}'")


def _parse_raw_type(data: dict[str, object], where: str) -> tuple[str, str, str]:
    kind = _expect_str(data, "kind", where)
    if kind in ("scalar", "const_ptr_scalar", "mut_ptr_scalar"):
        return (kind, _expect_str(data, "scalar", where), "")
    if kind in ("const_ptr_mirror", "mut_ptr_mirror", "enum_repr"):
        return (kind, "", _expect_str(data, "name", where))
    raise GenError(f"{where}: unknown raw type kind '{kind}'")


# One crate today, by design: the plan's crate->output-directory mapping stays unbuilt until a second exporting crate exists, and this check is what keeps that day loud instead of silently merging a new crate's bindings into core's files.
def _check_crate(data: dict[str, object], where: str) -> None:
    crate = _expect_str(data, "crate_name", where)
    if crate != "buckminster-core":
        raise GenError(f"{where}: crate '{crate}' has no output mapping; teach ffigen the crate->directory mapping before adding exporting crates")


def _parse_dump(dump_path: str) -> tuple[list[Export], list[Struct], list[Enum], list[Trait]]:
    with open(dump_path, encoding="utf-8") as handle:
        parsed: object = json.load(handle)
    if not isinstance(parsed, dict):
        raise GenError("dump root must be an object")
    root: dict[str, object] = {str(k): v for k, v in parsed.items()}  # pyright: ignore[reportUnknownVariableType, reportUnknownArgumentType]

    exports: list[Export] = []
    for data in _expect_list(root, "exports", "dump"):
        symbol = _expect_str(data, "symbol", "export")
        _check_crate(data, symbol)
        params: list[Param] = []
        for param in _expect_list(data, "params", symbol):
            params.append(Param(name=_expect_str(param, "name", symbol), ty=_parse_type(_expect_obj(param, "ty", symbol), symbol)))
        returns: list[Ret] = []
        for ret in _expect_list(data, "returns", symbol):
            returns.append(Ret(name=_expect_str(ret, "name", symbol), ty=_parse_type(_expect_obj(ret, "ty", symbol), symbol)))
        raw_params: list[RawParam] = []
        for raw in _expect_list(data, "raw_params", symbol):
            kind, scalar, mirror = _parse_raw_type(_expect_obj(raw, "ty", symbol), symbol)
            raw_params.append(RawParam(name=_expect_str(raw, "name", symbol), kind=kind, scalar=scalar, mirror_name=mirror))
        exports.append(Export(
            name=_expect_str(data, "name", symbol),
            symbol=symbol,
            docs=_expect_str_list(data, "docs", symbol),
            public=_expect_bool(data, "public", symbol),
            params=tuple(params),
            returns=tuple(returns),
            raw_params=tuple(raw_params),
        ))

    structs: list[Struct] = []
    for data in _expect_list(root, "structs", "dump"):
        name = _expect_str(data, "name", "struct")
        _check_crate(data, name)
        fields: list[Field] = []
        for field in _expect_list(data, "fields", name):
            fields.append(Field(name=_expect_str(field, "name", name), ty=_parse_type(_expect_obj(field, "ty", name), name), docs=_expect_str_list(field, "docs", name)))
        structs.append(Struct(name=name, docs=_expect_str_list(data, "docs", name), public=_expect_bool(data, "public", name), fields=tuple(fields)))

    enums: list[Enum] = []
    for data in _expect_list(root, "enums", "dump"):
        name = _expect_str(data, "name", "enum")
        _check_crate(data, name)
        variants = tuple(Variant(name=_expect_str(v, "name", name), value=_expect_int(v, "value", name), docs=_expect_str_list(v, "docs", name)) for v in _expect_list(data, "variants", name))
        enums.append(Enum(name=name, docs=_expect_str_list(data, "docs", name), public=_expect_bool(data, "public", name), repr_scalar=_expect_str(data, "repr", name), variants=variants))

    traits: list[Trait] = []
    for data in _expect_list(root, "traits", "dump"):
        name = _expect_str(data, "name", "trait")
        _check_crate(data, name)
        methods: list[Method] = []
        for entry in _expect_list(data, "methods", name):
            method_name = f"{name}.{_expect_str(entry, 'name', name)}"
            method_params: list[Param] = []
            for param in _expect_list(entry, "params", method_name):
                method_params.append(Param(name=_expect_str(param, "name", method_name), ty=_parse_type(_expect_obj(param, "ty", method_name), method_name)))
            method_returns: list[Ret] = []
            for ret in _expect_list(entry, "returns", method_name):
                method_returns.append(Ret(name=_expect_str(ret, "name", method_name), ty=_parse_type(_expect_obj(ret, "ty", method_name), method_name)))
            method_raws: list[RawParam] = []
            for raw in _expect_list(entry, "raw_params", method_name):
                kind, scalar, mirror = _parse_raw_type(_expect_obj(raw, "ty", method_name), method_name)
                method_raws.append(RawParam(name=_expect_str(raw, "name", method_name), kind=kind, scalar=scalar, mirror_name=mirror))
            methods.append(Method(name=_expect_str(entry, "name", name), docs=_expect_str_list(entry, "docs", method_name), params=tuple(method_params), returns=tuple(method_returns), raw_params=tuple(method_raws)))
        traits.append(Trait(name=name, docs=_expect_str_list(data, "docs", name), vtable=_expect_str(data, "vtable", name), methods=tuple(methods)))

    return exports, structs, enums, traits


def _pascal(snake: str) -> str:
    return "".join(part.capitalize() for part in snake.split("_"))


def _camel(snake: str) -> str:
    name = _pascal(snake)
    return name[0].lower() + name[1:]


def _out_name(raw_name: str, symbol: str) -> str:
    if not raw_name.startswith("out_"):
        raise GenError(f"{symbol}: return raw param '{raw_name}' does not start with out_")
    return _camel(raw_name.removeprefix("out_"))


def _xml_escape(text: str) -> str:
    # XML entity escaping only: /// doc text is element content, so "--" is legal here (the MSB4025 double-hyphen landmine applies to <!-- --> comment nodes in project files, not doc comments).
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _doc_lines(docs: tuple[str, ...], indent: str) -> list[str]:
    if not docs:
        return []
    lines = [f"{indent}/// <summary>"]
    for line in docs:
        lines.append(f"{indent}/// {_xml_escape(line)}".rstrip())
    lines.append(f"{indent}/// </summary>")
    return lines


@dataclass(frozen=True)
class _Mirrors:
    """Name resolution for mirror references: a mirror must exist as a generated struct or enum, and the two carry different C# semantics."""

    structs: dict[str, Struct]
    enums: dict[str, Enum]

    def struct(self, name: str, where: str) -> Struct:
        if name in self.enums:
            raise GenError(f"{where}: mirror '{name}' is an enum; enums cross as their repr scalar, not by reference")
        found = self.structs.get(name)
        if found is None:
            raise GenError(f"{where}: mirror '{name}' is not a generated struct (drifted dump?)")
        return found

    def is_enum(self, name: str) -> bool:
        return name in self.enums

    def enum_(self, name: str, where: str) -> Enum:
        found = self.enums.get(name)
        if found is None:
            raise GenError(f"{where}: mirror '{name}' is not a generated enum (drifted dump?)")
        return found


def _scalar_cs(scalar: str, where: str) -> str:
    found = _SCALAR_CS.get(scalar)
    if found is None:
        raise GenError(f"{where}: unknown scalar '{scalar}'")
    return found


# The raw scalar a semantic scalar must have been recorded as: identity, except bool (which the macro records as u8 -- bool never appears in a raw signature).
def _expected_raw_scalar(semantic_scalar: str) -> str:
    return "u8" if semantic_scalar == "bool" else semantic_scalar


def _raw_scalar_cs(scalar: str, where: str) -> str:
    if scalar == "bool":
        raise GenError(f"{where}: raw signatures never contain bool (the macro records u8); drifted dump?")
    return _scalar_cs(scalar, where)


def _elem_cs(elem: "TypeRef | None", mirrors: "_Mirrors", where: str) -> str:
    if elem is None:
        raise GenError(f"{where}: slice type is missing its element")
    if elem.kind == "scalar":
        if elem.scalar == "bool":
            raise GenError(f"{where}: bool slices are outside the vocabulary")
        return _scalar_cs(elem.scalar, where)
    if elem.kind == "mirror":
        return mirrors.struct(elem.mirror_name, where).name
    raise GenError(f"{where}: unsupported slice element kind '{elem.kind}'")


# One raw extern parameter's C# declaration, derived by zipping semantic roles onto the macro-authored raw list. The zip ASSERTS the raw name, kind, AND payload (scalar / mirror name) match what the semantic walk predicts -- a mismatch means the macro and this emitter disagree on the expansion rules, which is exactly the drift this design exists to catch.
def _import_params(export: Export, mirrors: _Mirrors) -> list[str]:
    raw = list(export.raw_params)
    declarations: list[str] = []

    def take(expected_name: str, expected_kind: str, expected_scalar: str = "", expected_mirror: str = "") -> RawParam:
        if not raw:
            raise GenError(f"{export.symbol}: raw signature ran out of params at '{expected_name}' (macro/emitter derivation drift)")
        head = raw.pop(0)
        if head.name != expected_name or head.kind != expected_kind:
            raise GenError(f"{export.symbol}: raw param mismatch: expected {expected_name}/{expected_kind}, recorded {head.name}/{head.kind} (macro/emitter derivation drift)")
        if expected_scalar and head.scalar != expected_scalar:
            raise GenError(f"{export.symbol}: raw param '{head.name}' recorded as scalar {head.scalar}, expected {expected_scalar} (macro/emitter derivation drift)")
        if expected_mirror and head.mirror_name != expected_mirror:
            raise GenError(f"{export.symbol}: raw param '{head.name}' recorded as mirror {head.mirror_name}, expected {expected_mirror} (macro/emitter derivation drift)")
        return head

    for param in export.params:
        if param.ty.kind == "scalar":
            head = take(param.name, "scalar", expected_scalar=_expected_raw_scalar(param.ty.scalar))
            declarations.append(f"{_raw_scalar_cs(head.scalar, export.symbol)} {_camel(param.name)}")
        elif param.ty.kind == "rid":
            take(param.name, "scalar", expected_scalar="u64")
            declarations.append(f"ulong {_camel(param.name)}")
        elif param.ty.kind == "mirror" and mirrors.is_enum(param.ty.mirror_name):
            take(param.name, "enum_repr", expected_mirror=param.ty.mirror_name)
            declarations.append(f"{mirrors.enum_(param.ty.mirror_name, export.symbol).name} {_camel(param.name)}")
        elif param.ty.kind == "mirror":
            head = take(param.name, "const_ptr_mirror", expected_mirror=param.ty.mirror_name)
            declarations.append(f"in {mirrors.struct(head.mirror_name, export.symbol).name} {_camel(param.name)}")
        elif param.ty.kind == "str":
            take(f"{param.name}_ptr", "const_ptr_scalar", expected_scalar="u8")
            take(f"{param.name}_len", "scalar", expected_scalar="usize")
            declarations.append(f"byte* {_camel(param.name)}Ptr")
            declarations.append(f"nuint {_camel(param.name)}Len")
        elif param.ty.kind == "slice_out":
            elem = param.ty.elem
            elem_cs = _elem_cs(elem, mirrors, export.symbol)
            if elem is not None and elem.kind == "mirror":
                take(f"{param.name}_ptr", "mut_ptr_mirror", expected_mirror=elem.mirror_name)
            else:
                take(f"{param.name}_ptr", "mut_ptr_scalar", expected_scalar=elem.scalar if elem else "")
            take(f"{param.name}_cap", "scalar", expected_scalar="usize")
            declarations.append(f"{elem_cs}* {_camel(param.name)}Ptr")
            declarations.append(f"nuint {_camel(param.name)}Cap")
        else:
            raise GenError(f"{export.symbol}: parameter shape '{param.ty.kind}' has no converted consumer yet; its emission lands with its first consumer")

    for ret in export.returns:
        if ret.ty.kind == "scalar":
            head = take(f"out_{ret.name}", "mut_ptr_scalar", expected_scalar=_expected_raw_scalar(ret.ty.scalar))
            declarations.append(f"out {_raw_scalar_cs(head.scalar, export.symbol)} {_out_name(head.name, export.symbol)}")
        elif ret.ty.kind == "rid":
            head = take(f"out_{ret.name}", "mut_ptr_scalar", expected_scalar="u64")
            declarations.append(f"out ulong {_out_name(head.name, export.symbol)}")
        elif ret.ty.kind == "mirror":
            head = take(f"out_{ret.name}", "mut_ptr_mirror", expected_mirror=ret.ty.mirror_name)
            declarations.append(f"out {mirrors.struct(head.mirror_name, export.symbol).name} {_out_name(head.name, export.symbol)}")
        else:
            raise GenError(f"{export.symbol}: return shape '{ret.ty.kind}' has no converted consumer yet; its emission lands with its first consumer")

    if raw:
        raise GenError(f"{export.symbol}: raw signature has {len(raw)} unconsumed params starting at '{raw[0].name}' (macro/emitter derivation drift)")
    return declarations


def _wrapper(export: Export, mirrors: _Mirrors) -> list[str]:
    params: list[str] = []
    arguments: list[str] = []
    # Statements before any fixed block (byte[] allocations for string marshaling), then one fixed block per pinned span/array.
    prelude: list[str] = []
    pins: list[tuple[str, str]] = []
    for param in export.params:
        name = _camel(param.name)
        if param.ty.kind == "scalar" and param.ty.scalar == "bool":
            params.append(f"bool {name}")
            arguments.append(f"(byte)({name} ? 1 : 0)")
        elif param.ty.kind == "scalar":
            params.append(f"{_scalar_cs(param.ty.scalar, export.symbol)} {name}")
            arguments.append(name)
        elif param.ty.kind == "rid":
            params.append(f"ulong {name}")
            arguments.append(name)
        elif param.ty.kind == "mirror" and mirrors.is_enum(param.ty.mirror_name):
            params.append(f"{mirrors.enum_(param.ty.mirror_name, export.symbol).name} {name}")
            arguments.append(name)
        elif param.ty.kind == "mirror":
            params.append(f"in {mirrors.struct(param.ty.mirror_name, export.symbol).name} {name}")
            arguments.append(f"in {name}")
        elif param.ty.kind == "str":
            params.append(f"string {name}")
            prelude.append(f"byte[] {name}Bytes = Encoding.UTF8.GetBytes({name});")
            pins.append((f"byte* {name}Ptr", f"{name}Bytes"))
            arguments.append(f"{name}Ptr")
            arguments.append(f"(nuint){name}Bytes.Length")
        elif param.ty.kind == "slice_out":
            elem_cs = _elem_cs(param.ty.elem, mirrors, export.symbol)
            params.append(f"Span<{elem_cs}> {name}")
            pins.append((f"{elem_cs}* {name}Ptr", name))
            arguments.append(f"{name}Ptr")
            arguments.append(f"(nuint){name}.Length")
        else:
            raise GenError(f"{export.symbol}: parameter shape '{param.ty.kind}' has no converted consumer yet; its emission lands with its first consumer")

    # Returns: each becomes an out argument; the wrapper surfaces one as a return value or several as a named tuple. usize returns surface as checked int (counts feel like C# ints; the raw layer stays nuint).
    return_types: list[str] = []
    return_exprs: list[str] = []
    for ret in export.returns:
        result = _camel(ret.name)
        if ret.ty.kind == "scalar" and ret.ty.scalar == "bool":
            arguments.append(f"out byte {result}")
            return_types.append("bool")
            return_exprs.append(f"{result} != 0")
        elif ret.ty.kind == "scalar" and ret.ty.scalar == "usize":
            arguments.append(f"out nuint {result}")
            return_types.append("int")
            return_exprs.append(f"checked((int){result})")
        elif ret.ty.kind == "scalar":
            cs_type = _scalar_cs(ret.ty.scalar, export.symbol)
            arguments.append(f"out {cs_type} {result}")
            return_types.append(cs_type)
            return_exprs.append(result)
        elif ret.ty.kind == "rid":
            arguments.append(f"out ulong {result}")
            return_types.append("ulong")
            return_exprs.append(result)
        elif ret.ty.kind == "mirror":
            cs_type = mirrors.struct(ret.ty.mirror_name, export.symbol).name
            arguments.append(f"out {cs_type} {result}")
            return_types.append(cs_type)
            return_exprs.append(result)
        else:
            raise GenError(f"{export.symbol}: return shape '{ret.ty.kind}' has no converted consumer yet; its emission lands with its first consumer")

    if not return_types:
        declared_return = "void"
        return_statement = ""
    elif len(return_types) == 1:
        declared_return = return_types[0]
        return_statement = f"return {return_exprs[0]};"
    else:
        fields = ", ".join(f"{ty} {_pascal(ret.name)}" for ty, ret in zip(return_types, export.returns))
        declared_return = f"({fields})"
        return_statement = f"return ({', '.join(return_exprs)});"

    method = _pascal(export.name)
    visibility = "public" if export.public else "internal"
    unsafe = "unsafe " if pins else ""
    lines = _doc_lines(export.docs, "    ")
    lines.append(f"    {visibility} static {unsafe}{declared_return} {method}({', '.join(params)})")
    lines.append("    {")
    indent = "        "
    for statement in prelude:
        lines.append(f"{indent}{statement}")
    for declaration, pinned in pins:
        lines.append(f"{indent}fixed ({declaration} = {pinned})")
        lines.append(f"{indent}{{")
        indent += "    "
    lines.append(f"{indent}FfiCall.ThrowOnError(NativeMethods.{export.symbol}({', '.join(arguments)}), \"{export.symbol}\");")
    if return_statement:
        lines.append(f"{indent}{return_statement}")
    for _ in pins:
        indent = indent[:-4]
        lines.append(f"{indent}}}")
    lines.append("    }")
    return lines


def _emit_native_methods(exports: list[Export], structs: list[Struct], mirrors: _Mirrors) -> str:
    lines = [_HEADER]
    lines.append("using System.Runtime.InteropServices;")
    lines.append("")
    lines.append("namespace Buckminster.Ffi;")
    lines.append("")
    lines.append("// The generated raw import layer: native snake_case names for 1:1 greppability against the Rust exports, FfiCode returns, out-params unspecified on nonzero return. The hand-written part of this class holds only buck_last_error_message and the shared Library constant.")
    lines.append("internal static partial class NativeMethods")
    lines.append("{")
    first = True
    for export in exports:
        if not first:
            lines.append("")
        first = False
        declarations = _import_params(export, mirrors)
        unsafe = "unsafe " if any("*" in declaration for declaration in declarations) else ""
        lines.append("    [LibraryImport(Library)]")
        lines.append(f"    internal static {unsafe}partial FfiCode {export.symbol}({', '.join(declarations)});")
    for struct in structs:
        if not first:
            lines.append("")
        first = False
        lines.append("    [LibraryImport(Library)]")
        lines.append(f"    internal static unsafe partial FfiCode buck_layout_{_snake(struct.name)}(ulong* bufPtr, nuint bufCap);")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _emit_native_wrappers(exports: list[Export], mirrors: _Mirrors) -> str:
    lines = [_HEADER]
    # Usings only when a wrapper actually needs them (Span / Encoding), so simple dumps emit simple files.
    kinds = {param.ty.kind for export in exports for param in export.params}
    if "slice_out" in kinds:
        lines.append("using System;")
    if "str" in kinds:
        lines.append("using System.Text;")
    if kinds & {"slice_out", "str"}:
        lines.append("")
    lines.append("namespace Buckminster.Ffi;")
    lines.append("")
    lines.append("// The generated idiomatic layer over NativeMethods: PascalCase, values in, return values out, failures as exceptions (FfiCall.ThrowOnError -- the FFI-problem channel; domain outcomes are ordinary returned data by convention).")
    lines.append("internal static partial class Native")
    lines.append("{")
    first = True
    for export in exports:
        if not first:
            lines.append("")
        first = False
        lines.extend(_wrapper(export, mirrors))
    lines.append("}")
    return "\n".join(lines) + "\n"


# Keep in step with pascal_to_snake in src/ffi-macros/rust/mirror.rs: both derive the buck_layout_* symbol, and divergence surfaces only as EntryPointNotFound in the generated layout test.
def _snake(pascal_name: str) -> str:
    snake = ""
    for index, character in enumerate(pascal_name):
        if character.isupper() and index != 0:
            snake += "_"
        snake += character.lower()
    return snake


def _field_cs_type(field: Field, struct: Struct, mirrors: _Mirrors) -> str:
    if field.ty.kind == "scalar":
        if field.ty.scalar == "bool":
            raise GenError(f"{struct.name}.{field.name}: bool fields are outside the vocabulary")
        return _scalar_cs(field.ty.scalar, struct.name)
    if field.ty.kind == "fn_ptr":
        # #[buck_trait] vtable fields: fn pointers cross as IntPtr (the standing wasm binding constraint).
        return "IntPtr"
    if field.ty.kind == "mirror":
        raise GenError(f"{struct.name}.{field.name}: mirrored-struct fields have no converted consumer yet; their emission lands with their first consumer")
    raise GenError(f"{struct.name}.{field.name}: unsupported field type kind '{field.ty.kind}'")


def _emit_struct(struct: Struct, mirrors: _Mirrors) -> str:
    namespace = "Buckminster" if struct.public else "Buckminster.Ffi"
    visibility = "public" if struct.public else "internal"
    lines = [_HEADER]
    if any(field.ty.kind == "fn_ptr" for field in struct.fields):
        lines.append("using System;")
    lines.append("using System.Runtime.InteropServices;")
    lines.append("")
    lines.append(f"namespace {namespace};")
    lines.append("")
    lines.extend(_doc_lines(struct.docs, ""))
    lines.append("[StructLayout(LayoutKind.Sequential)]")
    lines.append(f"{visibility} struct {struct.name}")
    lines.append("{")
    for index, field in enumerate(struct.fields):
        if index != 0:
            lines.append("")
        lines.extend(_doc_lines(field.docs, "    "))
        lines.append(f"    public {_field_cs_type(field, struct, mirrors)} {_pascal(field.name)};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _emit_enum(enum: Enum) -> str:
    namespace = "Buckminster" if enum.public else "Buckminster.Ffi"
    visibility = "public" if enum.public else "internal"
    underlying = {"i32": "int", "u32": "uint"}.get(enum.repr_scalar)
    if underlying is None:
        raise GenError(f"{enum.name}: unsupported enum repr '{enum.repr_scalar}'")
    lines = [_HEADER]
    lines.append(f"namespace {namespace};")
    lines.append("")
    lines.extend(_doc_lines(enum.docs, ""))
    declaration = f"{visibility} enum {enum.name}"
    if underlying != "int":
        declaration += f" : {underlying}"
    lines.append(declaration)
    lines.append("{")
    for variant in enum.variants:
        lines.extend(_doc_lines(variant.docs, "    "))
        lines.append(f"    {variant.name} = {variant.value},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _emit_layout_tests(structs: list[Struct]) -> str:
    lines = [_HEADER]
    lines.append("using System;")
    lines.append("using System.Runtime.InteropServices;")
    lines.append("using Buckminster;")
    lines.append("using Buckminster.Ffi;")
    lines.append("using NUnit.Framework;")
    lines.append("")
    lines.append("namespace Buckminster.Tests;")
    lines.append("")
    lines.append("// The layout-assertion seam, generated per mirrored struct: both sides derive from one Rust definition, but the comparison is rustc's computed layout against the CLR's -- an emitter bug or ABI disagreement still fails loudly, on every target.")
    lines.append("[TestFixture]")
    lines.append("public class LayoutTests")
    lines.append("{")
    first = True
    for struct in structs:
        if not first:
            lines.append("")
        first = False
        slots = len(struct.fields) + 1
        lines.append("    [Test]")
        lines.append(f"    public void {struct.name}LayoutMatchesRust()")
        lines.append("    {")
        lines.append(f"        Span<ulong> layout = stackalloc ulong[{slots}];")
        lines.append("        unsafe")
        lines.append("        {")
        lines.append("            fixed (ulong* pointer = layout)")
        lines.append("            {")
        lines.append(f"                Assert.That(NativeMethods.buck_layout_{_snake(struct.name)}(pointer, (nuint)layout.Length), Is.EqualTo(FfiCode.Ok));")
        lines.append("            }")
        lines.append("        }")
        lines.append(f"        Assert.That((ulong)Marshal.SizeOf<{struct.name}>(), Is.EqualTo(layout[0]));")
        for index, field in enumerate(struct.fields):
            lines.append(f"        Assert.That((ulong)(long)Marshal.OffsetOf<{struct.name}>(nameof({struct.name}.{_pascal(field.name)})), Is.EqualTo(layout[{index + 1}]));")
        lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _add_file(files: dict[str, str], name: str, content: str) -> None:
    # The collision fence: two declarations sharing one C# name (struct vs enum, a mirror named Native/NativeMethods/LayoutTests, ...) must be a loud generator error, never a silent file clobber.
    if name in files:
        raise GenError(f"duplicate generated file '{name}': two declarations share the C# name")
    files[name] = content


# The same role-zip discipline as _import_params, for a trait method's thunk: semantic params consume the macro-authored raw list with name/kind/payload assertions, and the walk produces the thunk parameter declarations, the reverse-marshal statements, and the interface-call arguments together so they cannot disagree.
def _thunk_pieces(trait: Trait, method: Method, mirrors: _Mirrors) -> tuple[list[str], list[str], list[str], str, str]:
    where = f"{trait.name}.{method.name}"
    raw = list(method.raw_params)

    def take(expected_name: str, expected_kind: str, expected_scalar: str = "", expected_mirror: str = "") -> RawParam:
        if not raw:
            raise GenError(f"{where}: raw signature ran out of params at '{expected_name}' (macro/emitter derivation drift)")
        head = raw.pop(0)
        if head.name != expected_name or head.kind != expected_kind:
            raise GenError(f"{where}: raw param mismatch: expected {expected_name}/{expected_kind}, recorded {head.name}/{head.kind} (macro/emitter derivation drift)")
        if expected_scalar and head.scalar != expected_scalar:
            raise GenError(f"{where}: raw param '{head.name}' recorded as scalar {head.scalar}, expected {expected_scalar} (macro/emitter derivation drift)")
        if expected_mirror and head.mirror_name != expected_mirror:
            raise GenError(f"{where}: raw param '{head.name}' recorded as mirror {head.mirror_name}, expected {expected_mirror} (macro/emitter derivation drift)")
        return head

    thunk_params: list[str] = ["ulong userdata"]
    marshal: list[str] = []
    call_args: list[str] = []
    for param in method.params:
        name = _camel(param.name)
        if param.ty.kind == "scalar" and param.ty.scalar == "bool":
            raise GenError(f"{where}: bool trait-method params have no consumer yet; their emission lands with their first consumer")
        elif param.ty.kind == "scalar":
            head = take(param.name, "scalar", expected_scalar=param.ty.scalar)
            thunk_params.append(f"{_raw_scalar_cs(head.scalar, where)} {name}")
            call_args.append(name)
        elif param.ty.kind == "mirror" and mirrors.is_enum(param.ty.mirror_name):
            take(param.name, "enum_repr", expected_mirror=param.ty.mirror_name)
            thunk_params.append(f"{mirrors.enum_(param.ty.mirror_name, where).name} {name}")
            call_args.append(name)
        elif param.ty.kind == "str":
            take(f"{param.name}_ptr", "const_ptr_scalar", expected_scalar="u8")
            take(f"{param.name}_len", "scalar", expected_scalar="usize")
            thunk_params.append(f"byte* {name}Ptr")
            thunk_params.append(f"nuint {name}Len")
            marshal.append(f"string {name} = {name}Len == 0 ? \"\" : Encoding.UTF8.GetString({name}Ptr, checked((int){name}Len));")
            call_args.append(name)
        else:
            raise GenError(f"{where}: trait-method parameter shape '{param.ty.kind}' has no consumer yet; its emission lands with its first consumer")

    interface_return = "void"
    invoke_statement = f"target.{_pascal(method.name)}({', '.join(call_args)});"
    if method.returns:
        if len(method.returns) > 1:
            raise GenError(f"{where}: multi-value trait-method returns have no consumer yet")
        ret = next(iter(method.returns))
        if ret.ty.kind != "scalar":
            raise GenError(f"{where}: trait-method return shape '{ret.ty.kind}' has no consumer yet")
        if ret.ty.scalar in ("bool", "usize"):
            raise GenError(f"{where}: {ret.ty.scalar} trait-method returns have no consumer yet; their emission lands with their first consumer")
        head = take("out_value", "mut_ptr_scalar", expected_scalar=_expected_raw_scalar(ret.ty.scalar))
        raw_cs = _raw_scalar_cs(head.scalar, where)
        thunk_params.append(f"{raw_cs}* outValue")
        interface_return = raw_cs
        invoke_statement = f"*outValue = target.{_pascal(method.name)}({', '.join(call_args)});"

    if raw:
        raise GenError(f"{where}: raw signature has {len(raw)} unconsumed params starting at '{raw[0].name}' (macro/emitter derivation drift)")
    return thunk_params, marshal, call_args, interface_return, invoke_statement


def _interface_params(trait: Trait, method: Method, mirrors: _Mirrors) -> list[str]:
    where = f"{trait.name}.{method.name}"
    declarations: list[str] = []
    for param in method.params:
        name = _camel(param.name)
        if param.ty.kind == "scalar" and param.ty.scalar == "bool":
            raise GenError(f"{where}: bool trait-method params have no consumer yet; their emission lands with their first consumer")
        elif param.ty.kind == "scalar":
            declarations.append(f"{_scalar_cs(param.ty.scalar, where)} {name}")
        elif param.ty.kind == "mirror" and mirrors.is_enum(param.ty.mirror_name):
            declarations.append(f"{mirrors.enum_(param.ty.mirror_name, where).name} {name}")
        elif param.ty.kind == "str":
            declarations.append(f"string {name}")
        else:
            raise GenError(f"{where}: trait-method parameter shape '{param.ty.kind}' has no consumer yet")
    return declarations


def _emit_trait_interface(trait: Trait, mirrors: _Mirrors) -> str:
    lines = [_HEADER]
    lines.append("namespace Buckminster;")
    lines.append("")
    lines.extend(_doc_lines(trait.docs, ""))
    lines.append(f"public interface I{trait.name}")
    lines.append("{")
    first = True
    for method in trait.methods:
        if not first:
            lines.append("")
        first = False
        lines.extend(_doc_lines(method.docs, "    "))
        _, _, _, interface_return, _ = _thunk_pieces(trait, method, mirrors)
        lines.append(f"    {interface_return} {_pascal(method.name)}({', '.join(_interface_params(trait, method, mirrors))});")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _emit_trait_thunks(trait: Trait, mirrors: _Mirrors) -> str:
    lines = [_HEADER]
    lines.append("using System;")
    lines.append("using System.Runtime.InteropServices;")
    if any(param.ty.kind == "str" for method in trait.methods for param in method.params):
        lines.append("using System.Text;")
    lines.append("")
    lines.append("namespace Buckminster.Ffi;")
    lines.append("")
    lines.append(f"// Bridges a C# I{trait.name} implementation into the {trait.vtable} Rust consumes: the canonical thunk shape (no exception escapes -- failures stash and return nonzero), CallbackTable registration, and a release thunk that unregisters (invoked by the Rust proxy's Drop: deterministic lifetime, no GC timing).")
    lines.append(f"internal static class {trait.name}Thunks")
    lines.append("{")
    lines.append(f"    internal static unsafe {trait.vtable} Create(I{trait.name} implementation)")
    lines.append("    {")
    lines.append(f"        return new {trait.vtable}")
    lines.append("        {")
    lines.append("            Userdata = CallbackTable.Register(implementation),")
    for method in trait.methods:
        thunk_params, _, _, _, _ = _thunk_pieces(trait, method, mirrors)
        delegate_types = ", ".join(declaration.split(" ")[0] for declaration in thunk_params)
        lines.append(f"            {_pascal(method.name)} = (IntPtr)(delegate* unmanaged<{delegate_types}, int>)&{_pascal(method.name)}Thunk,")
    lines.append("            Release = (IntPtr)(delegate* unmanaged<ulong, int>)&ReleaseThunk,")
    lines.append("        };")
    lines.append("    }")
    for method in trait.methods:
        thunk_params, marshal, _, _, invoke_statement = _thunk_pieces(trait, method, mirrors)
        unsafe = "unsafe " if any("*" in declaration for declaration in thunk_params) else ""
        lines.append("")
        lines.append("    [UnmanagedCallersOnly]")
        lines.append(f"    private static {unsafe}int {_pascal(method.name)}Thunk({', '.join(thunk_params)})")
        lines.append("    {")
        lines.append("        try")
        lines.append("        {")
        lines.append(f"            I{trait.name} target = (I{trait.name})CallbackTable.Get(userdata);")
        for statement in marshal:
            lines.append(f"            {statement}")
        lines.append(f"            {invoke_statement}")
        lines.append("            return 0;")
        lines.append("        }")
        lines.append("        catch (Exception exception)")
        lines.append("        {")
        lines.append("            CallbackExceptionStash.Stash(exception);")
        lines.append("            return 1;")
        lines.append("        }")
        lines.append("    }")
    lines.append("")
    lines.append("    [UnmanagedCallersOnly]")
    lines.append("    private static int ReleaseThunk(ulong userdata)")
    lines.append("    {")
    lines.append("        try")
    lines.append("        {")
    lines.append("            CallbackTable.Unregister(userdata);")
    lines.append("            return 0;")
    lines.append("        }")
    lines.append("        catch (Exception exception)")
    lines.append("        {")
    lines.append("            CallbackExceptionStash.Stash(exception);")
    lines.append("            return 1;")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _write_owned_dir(directory: str, files: dict[str, str]) -> None:
    """Writes the exact file set into the owned directory (write-if-changed so identical regeneration doesn't dirty dotnet; LF, UTF-8-no-BOM) and deletes strays."""
    os.makedirs(directory, exist_ok=True)
    for name, content in files.items():
        path = os.path.join(directory, name)
        if os.path.exists(path):
            with open(path, encoding="utf-8", newline="") as handle:
                if handle.read() == content:
                    continue
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
    for name in sorted(os.listdir(directory)):
        if name not in files:
            stray = os.path.join(directory, name)
            if not os.path.isfile(stray):
                raise GenError(f"unexpected non-file '{stray}' in an owned Generated/ directory; remove it by hand")
            print(f"ffigen: removing stray {stray}")
            os.remove(stray)


def generate(dump_path: str, repo_root: str) -> int:
    """Emits all generated C# from the dump. Returns a process-style exit code; failures print a loud GenError."""
    try:
        exports, structs, enums, traits = _parse_dump(dump_path)
        mirrors = _Mirrors(structs={struct.name: struct for struct in structs}, enums={enum.name: enum for enum in enums})

        methods: dict[str, str] = {}
        for export in exports:
            method = _pascal(export.name)
            if method in methods:
                raise GenError(f"wrapper name collision: '{methods[method]}' and '{export.name}' both PascalCase to {method}")
            methods[method] = export.name

        code_files: dict[str, str] = {}
        _add_file(code_files, "NativeMethods.g.cs", _emit_native_methods(exports, structs, mirrors))
        _add_file(code_files, "Native.g.cs", _emit_native_wrappers(exports, mirrors))
        for struct in structs:
            _add_file(code_files, f"{struct.name}.g.cs", _emit_struct(struct, mirrors))
        for enum in enums:
            _add_file(code_files, f"{enum.name}.g.cs", _emit_enum(enum))
        for trait in traits:
            _add_file(code_files, f"I{trait.name}.g.cs", _emit_trait_interface(trait, mirrors))
            _add_file(code_files, f"{trait.name}Thunks.g.cs", _emit_trait_thunks(trait, mirrors))
        test_files: dict[str, str] = {}
        _add_file(test_files, "LayoutTests.g.cs", _emit_layout_tests(structs))

        _write_owned_dir(os.path.join(repo_root, "src", "core", "cs", "Ffi", "Generated"), code_files)
        _write_owned_dir(os.path.join(repo_root, "src", "tests", "cs", "Generated"), test_files)
        return 0
    except GenError as error:
        print(f"Error: ffigen: {error}")
        return 1
