//! #[buck_struct] / #[buck_enum] expansion: the item stays untouched; alongside it land the BuckMirrored marker (always), the struct's layout-assertion export (always -- it verifies the generator's output at runtime on every target), and, under the exporting crate's ffi-dump feature, the BuckMirror identity impl plus inventory metadata for the C# emitter.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::{Fields, Ident, ItemEnum, ItemStruct};

use crate::shared::{self, Scalar};

/// EngineConfig -> engine_config, for the buck_layout_* symbol. Keep in step with _snake in tools/lib/ffigen.py: both derive the same symbol, and divergence surfaces only as EntryPointNotFound in the generated layout test.
fn pascal_to_snake(name: &str) -> String {
    let mut snake = String::new();
    for (index, character) in name.chars().enumerate() {
        if character.is_uppercase() && index != 0 {
            snake.push('_');
        }
        snake.push(character.to_ascii_lowercase());
    }
    snake
}

/// The layout-assertion seam, one export per mirrored struct (and per #[buck_trait] vtable): writes [size, offset per field] into the caller's buffer and demands the EXACT slot count, so a field-count drift between the two generated sides is loud instead of silently truncated.
pub fn layout_export(struct_name: &Ident, field_names: &[Ident]) -> TokenStream {
    let symbol = format_ident!("buck_layout_{}", pascal_to_snake(&struct_name.to_string()));
    let symbol_str = symbol.to_string();
    let expected = field_names.len() + 1;
    let count_message = format!(
        "{symbol_str}: expected exactly {expected} slots (size + one offset per field), got {{buf_cap}} -- the two generated sides disagree on the field count"
    );
    let null_message = format!("{symbol_str}: buf_ptr is null");
    let doc = format!(
        " Layout-assertion seam for `{struct_name}`, generated by #[buck_struct]: C# compares size and field offsets against its mirror on every target."
    );
    let indices = 1..=field_names.len();
    quote! {
        #[doc = #doc]
        #[doc = ""]
        #[doc = " # Safety"]
        #[doc = " `buf_ptr` must be non-null and writable for `buf_cap` u64 slots."]
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn #symbol(buf_ptr: *mut u64, buf_cap: usize) -> i32 {
            ::buckminster_core::ffi::guard(|| {
                if buf_cap != #expected {
                    return Err(::buckminster_core::ffi::FfiError::new(::buckminster_core::ffi::FfiCode::InvalidArgument, format!(#count_message)));
                }
                if buf_ptr.is_null() {
                    return Err(::buckminster_core::ffi::FfiError::new(::buckminster_core::ffi::FfiCode::InvalidArgument, #null_message));
                }
                let buf = unsafe { ::std::slice::from_raw_parts_mut(buf_ptr, buf_cap) };
                buf[0] = ::std::mem::size_of::<#struct_name>() as u64;
                #(buf[#indices] = ::std::mem::offset_of!(#struct_name, #field_names) as u64;)*
                Ok(())
            })
        }
    }
}

pub fn expand_struct(attr: TokenStream, item: TokenStream) -> syn::Result<TokenStream> {
    let args = shared::parse_args(attr, false, false)?;
    let item: ItemStruct = syn::parse2(item)?;
    if !shared::has_repr(&item.attrs, "C") {
        return Err(syn::Error::new_spanned(
            &item.ident,
            "#[buck_struct] requires #[repr(C)] (place #[buck_struct] ABOVE #[repr(C)] so it can see it)",
        ));
    }
    if !item.generics.params.is_empty() {
        return Err(syn::Error::new_spanned(
            &item.generics,
            "#[buck_struct] types cannot be generic",
        ));
    }
    let Fields::Named(fields) = &item.fields else {
        return Err(syn::Error::new_spanned(
            &item.ident,
            "#[buck_struct] requires named fields",
        ));
    };

    let name = item.ident.clone();
    let name_str = name.to_string();
    let field_names: Vec<Ident> = fields
        .named
        .iter()
        .map(|field| field.ident.clone().expect("named fields have idents"))
        .collect();
    let layout = layout_export(&name, &field_names);
    let mut meta_fields: Vec<TokenStream> = Vec::new();
    let mut assertions: Vec<TokenStream> = Vec::new();
    for field in &fields.named {
        let field_name = field
            .ident
            .as_ref()
            .expect("named fields have idents")
            .to_string();
        let field_docs = shared::docs_tokens(&shared::doc_lines(&field.attrs));
        let ty = match (Scalar::from_type(&field.ty), &field.ty) {
            (Some(Scalar::Bool), _) => {
                return Err(syn::Error::new_spanned(
                    &field.ty,
                    "bool fields are outside the FFI vocabulary (no C-ABI-agreed width in a mirrored struct); use u8",
                ));
            }
            (Some(scalar), _) => {
                let scalar = scalar.meta_tokens();
                quote!(::buckminster_core::ffi::meta::MetaType::Scalar { scalar: #scalar })
            }
            (None, syn::Type::Path(path)) => {
                let path = &path.path;
                assertions.push(shared::mirror_assertion(path));
                quote!(::buckminster_core::ffi::meta::MetaType::Mirror { crate_name: <#path as ::buckminster_core::ffi::meta::BuckMirror>::CRATE, name: <#path as ::buckminster_core::ffi::meta::BuckMirror>::NAME })
            }
            _ => {
                return Err(syn::Error::new_spanned(
                    &field.ty,
                    "unsupported field type: mirrored struct fields are scalars or other mirrored structs",
                ));
            }
        };
        meta_fields.push(quote!(::buckminster_core::ffi::meta::MetaField { name: #field_name, ty: #ty, docs: #field_docs }));
    }

    let docs = shared::docs_tokens(&shared::doc_lines(&item.attrs));
    let public = args.public;
    Ok(quote! {
        #item

        impl ::buckminster_core::ffi::BuckMirrored for #name {}

        #layout

        #(#assertions)*

        #[cfg(feature = "ffi-dump")]
        impl ::buckminster_core::ffi::meta::BuckMirror for #name {
            const CRATE: &'static str = ::core::env!("CARGO_PKG_NAME");
            const NAME: &'static str = #name_str;
        }

        #[cfg(feature = "ffi-dump")]
        ::buckminster_core::ffi::inventory::submit! {
            ::buckminster_core::ffi::meta::MetaStruct {
                crate_name: ::core::env!("CARGO_PKG_NAME"),
                name: #name_str,
                docs: #docs,
                public: #public,
                fields: &[#(#meta_fields),*],
            }
        }
    })
}

pub fn expand_enum(attr: TokenStream, item: TokenStream) -> syn::Result<TokenStream> {
    let args = shared::parse_args(attr, false, false)?;
    let item: ItemEnum = syn::parse2(item)?;
    let repr = if shared::has_repr(&item.attrs, "i32") {
        Scalar::I32
    } else if shared::has_repr(&item.attrs, "u32") {
        Scalar::U32
    } else {
        return Err(syn::Error::new_spanned(
            &item.ident,
            "#[buck_enum] requires #[repr(i32)] or #[repr(u32)] (place #[buck_enum] ABOVE the repr so it can see it)",
        ));
    };

    let name = item.ident.clone();
    let name_str = name.to_string();
    let repr_ty = repr.raw_tokens();
    let mut from_raw_arms: Vec<TokenStream> = Vec::new();
    let mut meta_variants: Vec<TokenStream> = Vec::new();
    for variant in &item.variants {
        if !matches!(variant.fields, Fields::Unit) {
            return Err(syn::Error::new_spanned(
                &variant.ident,
                "#[buck_enum] variants must be unit variants",
            ));
        }
        let Some((_, discriminant)) = &variant.discriminant else {
            return Err(syn::Error::new_spanned(
                &variant.ident,
                "#[buck_enum] variants need explicit discriminants",
            ));
        };
        let value = shared::discriminant_value(discriminant)?;
        let variant_name = variant.ident.to_string();
        let variant_ident = variant.ident.clone();
        let variant_docs = shared::docs_tokens(&shared::doc_lines(&variant.attrs));
        // The literal needs the repr's own type or the match arms won't typecheck against Repr.
        let value_literal = match repr {
            Scalar::I32 => proc_macro2::Literal::i32_suffixed(value as i32),
            Scalar::U32 => proc_macro2::Literal::u32_suffixed(value as u32),
            _ => unreachable!("enum reprs are validated to i32/u32 above"),
        };
        from_raw_arms.push(quote!(#value_literal => Some(#name::#variant_ident),));
        meta_variants.push(quote!(::buckminster_core::ffi::meta::MetaVariant { name: #variant_name, value: #value, docs: #variant_docs }));
    }

    let docs = shared::docs_tokens(&shared::doc_lines(&item.attrs));
    let public = args.public;
    let repr_meta = repr.meta_tokens();
    Ok(quote! {
        #item

        impl ::buckminster_core::ffi::BuckMirrored for #name {}

        impl ::buckminster_core::ffi::BuckEnum for #name {
            type Repr = #repr_ty;

            fn buck_from_raw(raw: #repr_ty) -> Option<#name> {
                match raw {
                    #(#from_raw_arms)*
                    _ => None,
                }
            }

            fn buck_raw(self) -> #repr_ty {
                self as #repr_ty
            }
        }

        #[cfg(feature = "ffi-dump")]
        impl ::buckminster_core::ffi::meta::BuckMirror for #name {
            const CRATE: &'static str = ::core::env!("CARGO_PKG_NAME");
            const NAME: &'static str = #name_str;
        }

        #[cfg(feature = "ffi-dump")]
        ::buckminster_core::ffi::inventory::submit! {
            ::buckminster_core::ffi::meta::MetaEnum {
                crate_name: ::core::env!("CARGO_PKG_NAME"),
                name: #name_str,
                docs: #docs,
                public: #public,
                repr: #repr_meta,
                variants: &[#(#meta_variants),*],
            }
        }
    })
}
