//! #[buck_trait] expansion: C# implements a Rust trait through a generated #[repr(C)] vtable (one extern "C" fn pointer per method, u64 userdata key, and a release fn pointer -- M1's callback rails generalized from one function pointer to a struct of them). The trait is implemented FOR the vtable (borrowed invocation, no lifetime semantics) and for the owning {Trait}Proxy (Drop calls release, so the C#-side CallbackTable registration dies deterministically with the proxy). The C# half -- public interface, [UnmanagedCallersOnly] thunks, Create() glue -- is generated by ffigen from the dump metadata.
//!
//! Trait methods MUST return Result<T, FfiError>: the vtable fn's i32 return is the C# exception channel (thunks stash and return nonzero), and a method without the Result form would have nowhere to surface it -- pinned in PLAN's binding-generation entry, settled before build time.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::{FnArg, Ident, ItemTrait, Pat, TraitItem};

use crate::shared::{self, ParamKind, RetItem, Scalar};

struct Method {
    name: Ident,
    docs: Vec<String>,
    // The vtable field's fn-pointer parameter types (after the leading userdata) and the forwarding-call argument expressions, built together so they cannot disagree.
    raw_param_decls: Vec<TokenStream>,
    raw_metas: Vec<TokenStream>,
    forward_args: Vec<TokenStream>,
    idiomatic_params: Vec<TokenStream>,
    param_names: Vec<Ident>,
    meta_params: Vec<TokenStream>,
    meta_returns: Vec<TokenStream>,
    out_locals: Vec<TokenStream>,
    out_raw_decls: Vec<TokenStream>,
    result_ty: TokenStream,
    result_expr: TokenStream,
}

pub fn expand(attr: TokenStream, item: TokenStream) -> syn::Result<TokenStream> {
    // Trait interfaces default PUBLIC (they exist to be implemented by game code -- they ARE API); `internal` is the explicit, written-down exception for test/infra demonstrators that must not appear in game-facing surface.
    let args = shared::parse_args(attr, false, true)?;
    let item: ItemTrait = syn::parse2(item)?;
    if !item.generics.params.is_empty() {
        return Err(syn::Error::new_spanned(
            &item.generics,
            "#[buck_trait] traits cannot be generic",
        ));
    }

    let trait_name = item.ident.clone();
    let trait_name_str = trait_name.to_string();
    let vtable_name = format_ident!("{}Vtable", trait_name);
    let vtable_name_str = vtable_name.to_string();
    let proxy_name = format_ident!("{}Proxy", trait_name);
    let layout = crate::mirror::layout_export(&vtable_name, &collect_field_names(&item)?);

    let mut methods: Vec<Method> = Vec::new();
    for entry in &item.items {
        let TraitItem::Fn(method) = entry else {
            return Err(syn::Error::new_spanned(
                entry,
                "#[buck_trait] traits contain only methods",
            ));
        };
        if method.default.is_some() {
            return Err(syn::Error::new_spanned(
                &method.sig.ident,
                "#[buck_trait] methods are bodiless (the C# interface cannot carry a default body)",
            ));
        }
        methods.push(parse_method(method, &trait_name_str)?);
    }

    // --- vtable struct: userdata, one fn pointer per method (declaration order), release ---
    let vtable_fields: Vec<TokenStream> = methods
        .iter()
        .map(|method| {
            let name = &method.name;
            let params = &method.raw_param_decls;
            let outs = &method.out_raw_decls;
            quote!(pub #name: extern "C" fn(userdata: u64 #(, #params)* #(, #outs)*) -> i32)
        })
        .collect();

    // --- trait impl for the vtable: borrowed invocation, nonzero -> CallbackError ---
    let vtable_impls: Vec<TokenStream> = methods
        .iter()
        .map(|method| {
            let name = &method.name;
            let params = &method.idiomatic_params;
            let args = &method.forward_args;
            let out_locals = &method.out_locals;
            let result_ty = &method.result_ty;
            let result_expr = &method.result_expr;
            let message = format!("{trait_name_str}::{name} returned error code {{code}}");
            quote! {
                fn #name(&mut self #(, #params)*) -> ::core::result::Result<#result_ty, ::buckminster_core::ffi::FfiError> {
                    #(#out_locals)*
                    let code = (self.#name)(self.userdata #(, #args)*);
                    if code != 0 {
                        return Err(::buckminster_core::ffi::FfiError::new(::buckminster_core::ffi::FfiCode::CallbackError, format!(#message)));
                    }
                    Ok(#result_expr)
                }
            }
        })
        .collect();

    let proxy_forwards: Vec<TokenStream> = methods
        .iter()
        .map(|method| {
            let name = &method.name;
            let params = &method.idiomatic_params;
            let result_ty = &method.result_ty;
            let pass = &method.param_names;
            quote! {
                fn #name(&mut self #(, #params)*) -> ::core::result::Result<#result_ty, ::buckminster_core::ffi::FfiError> {
                    self.vtable.#name(#(#pass),*)
                }
            }
        })
        .collect();

    let meta_methods: Vec<TokenStream> = methods
        .iter()
        .map(|method| {
            let name = method.name.to_string();
            let docs = shared::docs_tokens(&method.docs);
            let params = &method.meta_params;
            let returns = &method.meta_returns;
            let raws = &method.raw_metas;
            quote!(::buckminster_core::ffi::meta::MetaMethod { name: #name, docs: #docs, params: &[#(#params),*], returns: &[#(#returns),*], raw_params: &[#(#raws),*] })
        })
        .collect();

    let vtable_meta_fields: Vec<TokenStream> = {
        let mut fields = vec![quote!(::buckminster_core::ffi::meta::MetaField {
            name: "userdata",
            ty: ::buckminster_core::ffi::meta::MetaType::Scalar {
                scalar: ::buckminster_core::ffi::meta::MetaScalar::U64
            },
            docs: &[]
        })];
        for method in &methods {
            let name = method.name.to_string();
            fields.push(quote!(::buckminster_core::ffi::meta::MetaField { name: #name, ty: ::buckminster_core::ffi::meta::MetaType::FnPtr, docs: &[] }));
        }
        fields.push(quote!(::buckminster_core::ffi::meta::MetaField {
            name: "release",
            ty: ::buckminster_core::ffi::meta::MetaType::FnPtr,
            docs: &[]
        }));
        fields
    };

    let docs = shared::docs_tokens(&shared::doc_lines(&item.attrs));
    let public = !args.internal;
    let vtable_doc = format!(
        " The C ABI carrier for `{trait_name_str}`: userdata key, one fn pointer per method, and release. Generated by #[buck_trait]; the C# mirror and thunks come from ffigen."
    );
    let proxy_doc = format!(
        " Owns a `{vtable_name_str}`: implements `{trait_name_str}` by forwarding, and Drop calls the release pointer so the C#-side registration dies with the proxy (deterministic lifetime, no GC timing)."
    );
    let release_warning = format!("{trait_name_str} release returned error code {{code}}");

    Ok(quote! {
        #item

        #[doc = #vtable_doc]
        #[repr(C)]
        #[derive(Clone, Copy)]
        pub struct #vtable_name {
            pub userdata: u64,
            #(#vtable_fields,)*
            pub release: extern "C" fn(userdata: u64) -> i32,
        }

        impl ::buckminster_core::ffi::BuckMirrored for #vtable_name {}

        #layout

        impl #trait_name for #vtable_name {
            #(#vtable_impls)*
        }

        #[doc = #proxy_doc]
        pub struct #proxy_name {
            vtable: #vtable_name,
        }

        impl #proxy_name {
            pub fn from_vtable(vtable: #vtable_name) -> #proxy_name {
                #proxy_name { vtable }
            }

            /// A copy of the vtable for borrowed invocation (the trait is implemented for the vtable itself) -- the pattern for calling under callback rule 4, where the owning proxy sits behind a lock that must not be held across the call.
            pub fn vtable(&self) -> #vtable_name {
                self.vtable
            }
        }

        impl #trait_name for #proxy_name {
            #(#proxy_forwards)*
        }

        impl Drop for #proxy_name {
            fn drop(&mut self) {
                // A failed release means a leaked registration -- error, not warn (release must never fail silently). The thunk stashed its exception C#-side; the stash's take-on-next-failure semantics attach it as InnerException to whatever surfaces next on this thread.
                let code = (self.vtable.release)(self.vtable.userdata);
                if code != 0 {
                    ::log::error!(#release_warning);
                }
            }
        }

        #[cfg(feature = "ffi-dump")]
        impl ::buckminster_core::ffi::meta::BuckMirror for #vtable_name {
            const CRATE: &'static str = ::core::env!("CARGO_PKG_NAME");
            const NAME: &'static str = #vtable_name_str;
        }

        #[cfg(feature = "ffi-dump")]
        ::buckminster_core::ffi::inventory::submit! {
            ::buckminster_core::ffi::meta::MetaStruct {
                crate_name: ::core::env!("CARGO_PKG_NAME"),
                name: #vtable_name_str,
                docs: &[#vtable_doc],
                public: false,
                fields: &[#(#vtable_meta_fields),*],
            }
        }

        #[cfg(feature = "ffi-dump")]
        ::buckminster_core::ffi::inventory::submit! {
            ::buckminster_core::ffi::meta::MetaTrait {
                crate_name: ::core::env!("CARGO_PKG_NAME"),
                name: #trait_name_str,
                docs: #docs,
                public: #public,
                vtable: #vtable_name_str,
                methods: &[#(#meta_methods),*],
            }
        }
    })
}

fn collect_field_names(item: &ItemTrait) -> syn::Result<Vec<Ident>> {
    let mut names = vec![format_ident!("userdata")];
    for entry in &item.items {
        if let TraitItem::Fn(method) = entry {
            // The reserved vtable field names would otherwise die as a raw duplicate-field rustc error deep in generated code.
            if method.sig.ident == "userdata" || method.sig.ident == "release" {
                return Err(syn::Error::new_spanned(
                    &method.sig.ident,
                    "#[buck_trait] methods cannot be named `userdata` or `release` (reserved vtable fields)",
                ));
            }
            names.push(method.sig.ident.clone());
        }
    }
    names.push(format_ident!("release"));
    Ok(names)
}

fn parse_method(method: &syn::TraitItemFn, trait_name: &str) -> syn::Result<Method> {
    let sig = &method.sig;
    if !sig.generics.params.is_empty() {
        return Err(syn::Error::new_spanned(
            &sig.generics,
            "#[buck_trait] methods cannot be generic",
        ));
    }
    let mut inputs = sig.inputs.iter();
    match inputs.next() {
        Some(FnArg::Receiver(receiver))
            if receiver.mutability.is_some() && receiver.reference.is_some() => {}
        _ => {
            return Err(syn::Error::new_spanned(
                sig,
                "#[buck_trait] methods take &mut self",
            ));
        }
    }

    let returns = shared::classify_returns(&sig.output)?;
    if !returns.fallible {
        return Err(syn::Error::new_spanned(
            &sig.output,
            "#[buck_trait] methods must return Result<T, FfiError>: the i32 code is the C# exception channel, and a plain form would have nowhere to surface it",
        ));
    }
    if returns.items.len() > 1 {
        return Err(syn::Error::new_spanned(
            &sig.output,
            "multi-value trait-method returns have no consumer yet; they land with their first consumer",
        ));
    }

    let name = sig.ident.clone();
    let context = format!("{trait_name}::{name}");
    let mut raw_param_decls: Vec<TokenStream> = Vec::new();
    let mut raw_metas: Vec<TokenStream> = Vec::new();
    let mut forward_args: Vec<TokenStream> = Vec::new();
    let mut idiomatic_params: Vec<TokenStream> = Vec::new();
    let mut param_names: Vec<Ident> = Vec::new();
    let mut meta_params: Vec<TokenStream> = Vec::new();

    for input in inputs {
        let FnArg::Typed(typed) = input else {
            return Err(syn::Error::new_spanned(input, "unexpected receiver"));
        };
        let Pat::Ident(pat) = &*typed.pat else {
            return Err(syn::Error::new_spanned(
                &typed.pat,
                "#[buck_trait] parameters must be plain identifiers",
            ));
        };
        let param_name = pat.ident.clone();
        let param_name_string = param_name.to_string();
        param_names.push(param_name.clone());
        let ty = &typed.ty;
        match shared::classify_param(ty)? {
            ParamKind::Scalar(scalar) => {
                let raw_ty = scalar.raw_tokens();
                let raw_scalar = scalar.raw_meta_tokens();
                let sem_scalar = scalar.meta_tokens();
                raw_param_decls.push(quote!(#param_name: #raw_ty));
                raw_metas.push(quote!(::buckminster_core::ffi::meta::MetaRawParam { name: #param_name_string, ty: ::buckminster_core::ffi::meta::MetaRawType::Scalar { scalar: #raw_scalar } }));
                if scalar == Scalar::Bool {
                    forward_args.push(quote!(#param_name as u8));
                } else {
                    forward_args.push(quote!(#param_name));
                }
                idiomatic_params.push(quote!(#param_name: #ty));
                meta_params.push(quote!(::buckminster_core::ffi::meta::MetaParam { name: #param_name_string, ty: ::buckminster_core::ffi::meta::MetaType::Scalar { scalar: #sem_scalar } }));
            }
            ParamKind::EnumVal(path) => {
                raw_param_decls
                    .push(quote!(#param_name: <#path as ::buckminster_core::ffi::BuckEnum>::Repr));
                raw_metas.push(quote!(::buckminster_core::ffi::meta::MetaRawParam { name: #param_name_string, ty: ::buckminster_core::ffi::meta::MetaRawType::EnumRepr { crate_name: <#path as ::buckminster_core::ffi::meta::BuckMirror>::CRATE, name: <#path as ::buckminster_core::ffi::meta::BuckMirror>::NAME } }));
                forward_args.push(quote!(::buckminster_core::ffi::BuckEnum::buck_raw(#param_name)));
                idiomatic_params.push(quote!(#param_name: #ty));
                meta_params.push(quote!(::buckminster_core::ffi::meta::MetaParam { name: #param_name_string, ty: ::buckminster_core::ffi::meta::MetaType::Mirror { crate_name: <#path as ::buckminster_core::ffi::meta::BuckMirror>::CRATE, name: <#path as ::buckminster_core::ffi::meta::BuckMirror>::NAME } }));
            }
            ParamKind::Str => {
                let ptr = format_ident!("{}_ptr", param_name);
                let len = format_ident!("{}_len", param_name);
                let ptr_string = ptr.to_string();
                let len_string = len.to_string();
                raw_param_decls.push(quote!(#ptr: *const u8));
                raw_param_decls.push(quote!(#len: usize));
                raw_metas.push(quote!(::buckminster_core::ffi::meta::MetaRawParam { name: #ptr_string, ty: ::buckminster_core::ffi::meta::MetaRawType::ConstPtrScalar { scalar: ::buckminster_core::ffi::meta::MetaScalar::U8 } }));
                raw_metas.push(quote!(::buckminster_core::ffi::meta::MetaRawParam { name: #len_string, ty: ::buckminster_core::ffi::meta::MetaRawType::Scalar { scalar: ::buckminster_core::ffi::meta::MetaScalar::USize } }));
                forward_args.push(quote!(#param_name.as_ptr()));
                forward_args.push(quote!(#param_name.len()));
                idiomatic_params.push(quote!(#param_name: &str));
                meta_params.push(quote!(::buckminster_core::ffi::meta::MetaParam { name: #param_name_string, ty: ::buckminster_core::ffi::meta::MetaType::Str }));
            }
            _ => {
                return Err(syn::Error::new_spanned(
                    ty,
                    format!(
                        "{context}: this parameter shape has no trait-method consumer yet; it lands with its first consumer (trait vocabulary today: scalars, enums, &str)"
                    ),
                ));
            }
        }
    }

    // Single optional return: an out-pointer at the tail of the fn-pointer signature, read after a zero return.
    let mut out_locals: Vec<TokenStream> = Vec::new();
    let mut out_raw_decls: Vec<TokenStream> = Vec::new();
    let mut raw_out_metas: Vec<TokenStream> = Vec::new();
    let mut meta_returns: Vec<TokenStream> = Vec::new();
    let (result_ty, result_expr) = match returns.items.first() {
        None => (quote!(()), quote!(())),
        Some(RetItem::Scalar(scalar)) => {
            let raw_ty = scalar.raw_tokens();
            let raw_scalar = scalar.raw_meta_tokens();
            let sem_scalar = scalar.meta_tokens();
            out_locals
                .push(quote!(let mut __out_value: #raw_ty = ::core::default::Default::default();));
            out_raw_decls.push(quote!(out_value: *mut #raw_ty));
            raw_out_metas.push(quote!(::buckminster_core::ffi::meta::MetaRawParam { name: "out_value", ty: ::buckminster_core::ffi::meta::MetaRawType::MutPtrScalar { scalar: #raw_scalar } }));
            meta_returns.push(quote!(::buckminster_core::ffi::meta::MetaReturn { name: "value", ty: ::buckminster_core::ffi::meta::MetaType::Scalar { scalar: #sem_scalar } }));
            let expr = if *scalar == Scalar::Bool {
                quote!(__out_value != 0)
            } else {
                quote!(__out_value)
            };
            let ty_tokens = if *scalar == Scalar::Bool {
                quote!(bool)
            } else {
                raw_ty
            };
            (ty_tokens, expr)
        }
        Some(_) => {
            return Err(syn::Error::new_spanned(
                &sig.output,
                "trait-method return shapes beyond scalars have no consumer yet; they land with their first consumer",
            ));
        }
    };

    let mut all_raw_metas = raw_metas;
    all_raw_metas.extend(raw_out_metas);

    let mut method = Method {
        name,
        docs: shared::doc_lines(&method.attrs),
        raw_param_decls,
        raw_metas: all_raw_metas,
        forward_args,
        idiomatic_params,
        param_names,
        meta_params,
        meta_returns,
        out_locals,
        out_raw_decls,
        result_ty,
        result_expr,
    };
    if !method.out_locals.is_empty() {
        method.forward_args.push(quote!(&mut __out_value));
    }
    Ok(method)
}

#[cfg(test)]
mod tests {
    use proc_macro2::TokenStream;
    use quote::quote;

    // Pins the vtable ABI the C# side mirrors: userdata leads, method pointers follow in declaration order, release trails; the proxy's Drop fires release; method metadata records the fn-pointer signature WITHOUT the leading userdata (the emitter prepends it). Assertions match proc-macro2 token stringification under the pinned toolchain.

    fn expand_string(item: TokenStream) -> String {
        super::expand(TokenStream::new(), item)
            .expect("expansion should succeed")
            .to_string()
    }

    #[test]
    fn vtable_shape_and_release_on_drop() {
        let expansion = expand_string(quote! {
            trait Probe {
                fn poke(&mut self, value: i32) -> Result<i32, FfiError>;
            }
        });
        assert!(
            expansion.contains("pub struct ProbeVtable"),
            "vtable struct: {expansion}"
        );
        assert!(
            expansion.contains("pub userdata : u64"),
            "userdata leads: {expansion}"
        );
        assert!(expansion.contains("pub poke : extern \"C\" fn (userdata : u64 , value : i32 , out_value : * mut i32) -> i32"), "method pointer signature: {expansion}");
        assert!(
            expansion.contains("pub release : extern \"C\" fn (userdata : u64) -> i32"),
            "release trails: {expansion}"
        );
        assert!(
            expansion.contains("impl Drop for ProbeProxy"),
            "proxy releases on drop: {expansion}"
        );
        assert!(
            expansion.contains("(self . vtable . release) (self . vtable . userdata)"),
            "drop calls release: {expansion}"
        );
        assert!(
            expansion.contains("buck_layout_probe_vtable"),
            "vtable joins the layout seam: {expansion}"
        );
        assert!(
            expansion.contains("impl Probe for ProbeVtable"),
            "borrowed invocation impl: {expansion}"
        );
    }

    #[test]
    fn internal_flag_marks_the_metadata_nonpublic() {
        let expansion = super::expand(
            quote!(internal),
            quote! {
                trait Probe {
                    fn poke(&mut self, value: i32) -> Result<i32, FfiError>;
                }
            },
        )
        .expect("expansion should succeed")
        .to_string();
        assert!(
            expansion.contains("public : false"),
            "internal traits record public: false for the emitter: {expansion}"
        );
    }

    #[test]
    fn method_metadata_omits_the_implicit_userdata() {
        let expansion = expand_string(quote! {
            trait Probe {
                fn poke(&mut self, value: i32) -> Result<i32, FfiError>;
            }
        });
        assert!(
            expansion.contains("MetaRawParam { name : \"value\""),
            "method raw param recorded: {expansion}"
        );
        assert!(
            expansion.contains("MetaRawParam { name : \"out_value\""),
            "out raw param recorded: {expansion}"
        );
        assert!(
            !expansion.contains("MetaRawParam { name : \"userdata\""),
            "userdata is the emitter's to prepend, never recorded: {expansion}"
        );
        assert!(
            expansion.contains("MetaField { name : \"userdata\""),
            "userdata IS a vtable field: {expansion}"
        );
        assert!(
            expansion.contains("MetaType :: FnPtr"),
            "method fields are fn pointers: {expansion}"
        );
    }
}
