<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../core/cs/Buckminster.Core.csproj" />
        <ProjectReference Include="../../usergame-demo/cs/Buckminster.Usergame.Demo.csproj" />
    </ItemGroup>

</Project>
